---
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: sato-mh/distributed-calculator/api-gateway
      docker: { dockerfile: Dockerfile.golang, network: host, buildArgs: { SERVICE_NAME: api/gateway } }
    - image: sato-mh/distributed-calculator/svc-greeter
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/greeter } }
    - image: sato-mh/distributed-calculator/svc-adder
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/adder } }
    - image: sato-mh/distributed-calculator/svc-subtractor
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/subtractor } }
    - image: sato-mh/distributed-calculator/svc-multiplier
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/multiplier } }
    - image: sato-mh/distributed-calculator/svc-divider
      docker: { dockerfile: Dockerfile.python, network: host, buildArgs: { SERVICE_NAME: svc/divider } }

deploy:
  kustomize:
    paths:
      - manifests/overlays/localhost
portForward:
  - resourceType: service
    resourceName: api-gateway
    namespace: default
    port: 8080
    localPort: 58080
  - resourceType: service
    resourceName: svc-greeter
    namespace: default
    port: 5050
    localPort: 55050
  - resourceType: service
    resourceName: svc-adder
    namespace: default
    port: 5050
    localPort: 55060
  - resourceType: service
    resourceName: svc-subtractor
    namespace: default
    port: 5050
    localPort: 55061
  - resourceType: service
    resourceName: svc-multiplier
    namespace: default
    port: 5050
    localPort: 55062
  - resourceType: service
    resourceName: svc-divider
    namespace: default
    port: 5050
    localPort: 55063
profiles:
  - name: localhost
  - name: production
    deploy:
      kustomize:
        paths:
          - manifests/overlays/production
