import os

SUBTRACTOR_DAPR_ADDRESS = 'localhost'
SUBTRACTOR_DAPR_PORT = 50001
SUBTRACTOR_ADDRESS = os.environ.get('SUBTRACTOR_ADDRESS', '0.0.0.0:5050')
IP_ADDRESS = SUBTRACTOR_ADDRESS.split(':')[0]
PORT = int(SUBTRACTOR_ADDRESS.split(':')[1])
